export const BUSINESS_CATEGORIES = [
  { key: "Restaurant", label: "Restaurant", icon: "🍽️", desc: "Full menus, ordering & delivery", kycType: "Restaurant" },
  { key: "Ecommerce", label: "Ecommerce", icon: "🛍️", desc: "Products, cart & checkout", kycType: "Retail" },
  { key: "Food Vendor", label: "Food Vendor", icon: "🥗", desc: "Bukas, home kitchens, caterers", kycType: "Restaurant" },
  { key: "Grocery", label: "Grocery", icon: "🛒", desc: "Supermarkets & local stores", kycType: "Retail" },
  { key: "Church", label: "Church", icon: "⛪", desc: "Events, giving & community", kycType: "Church" },
  { key: "School", label: "School", icon: "🏫", desc: "Timetables, fees & announcements", kycType: "School" },
  { key: "Booking", label: "Booking", icon: "📅", desc: "Appointments & scheduling", kycType: "Service" },
  { key: "Events", label: "Events", icon: "🎪", desc: "Tickets, RSVPs & event media", kycType: "Service" },
  { key: "Consulting", label: "Consulting", icon: "💼", desc: "Advisory services & invoices", kycType: "Service" },
  { key: "Nonprofit", label: "Nonprofit", icon: "🤝", desc: "Donations, causes & campaigns", kycType: "Nonprofit" },
  { key: "Personal", label: "Personal", icon: "🌟", desc: "Portfolio, landing page & contact", kycType: "Personal" },
];

export const ONBOARDING_CATEGORIES = [
  ...BUSINESS_CATEGORIES,
  { key: "Cafe", label: "Cafe", icon: "☕", desc: "Coffee, pastries & quick bites", kycType: "Restaurant" },
  { key: "Bar", label: "Bar & Lounge", icon: "🍸", desc: "Drinks, cocktails & nightlife", kycType: "Restaurant" },
  { key: "Pharmacy", label: "Pharmacy", icon: "💊", desc: "Medicines, health & wellness products", kycType: "Retail" },
  { key: "Beauty", label: "Beauty & Salon", icon: "💇‍♀️", desc: "Hair, nails & esthetics", kycType: "Service" },
  { key: "Spa", label: "Spa & Wellness", icon: "🧖", desc: "Massage, facials & self-care", kycType: "Service" },
  { key: "Fitness", label: "Fitness & Gym", icon: "🏋️", desc: "Workouts, classes & memberships", kycType: "Service" },
  { key: "Clinic", label: "Clinic & Healthcare", icon: "🩺", desc: "Appointments, records & care", kycType: "Service" },
  { key: "Dental", label: "Dental", icon: "🦷", desc: "Checkups, hygiene & treatments", kycType: "Service" },
  { key: "Optical", label: "Optical", icon: "👓", desc: "Eye tests, glasses & lenses", kycType: "Service" },
  { key: "Pet Care", label: "Pet Care", icon: "🐾", desc: "Grooming, boarding & vet visits", kycType: "Service" },
  { key: "Laundry", label: "Laundry", icon: "🧺", desc: "Wash, fold & dry cleaning", kycType: "Service" },
  { key: "Cleaning", label: "Cleaning", icon: "🧼", desc: "Home & office cleaning", kycType: "Service" },
  { key: "Barbershop", label: "Barbershop", icon: "💈", desc: "Cuts, fades & styling", kycType: "Service" },
  { key: "Tailor", label: "Tailor & Alterations", icon: "🧵", desc: "Custom fits & repairs", kycType: "Service" },
  { key: "Photography", label: "Photography", icon: "📸", desc: "Shoots, prints & albums", kycType: "Service" },
  { key: "Videography", label: "Videography", icon: "🎥", desc: "Film, edit & production", kycType: "Service" },
  { key: "Tech Repair", label: "Tech Repair", icon: "🔧", desc: "Phones, laptops & gadgets", kycType: "Service" },
  { key: "Real Estate", label: "Real Estate", icon: "🏠", desc: "Sales, rentals & property", kycType: "Service" },
  { key: "Travel", label: "Travel & Tours", icon: "✈️", desc: "Trips, bookings & packages", kycType: "Service" },
  { key: "Logistics", label: "Logistics & Delivery", icon: "📦", desc: "Courier, dispatch & moving", kycType: "Service" },
  { key: "Car Wash", label: "Car Wash", icon: "🚗", desc: "Detailing & auto care", kycType: "Service" },
  { key: "Auto Repair", label: "Auto Repair", icon: "🔩", desc: "Service & maintenance", kycType: "Service" },
  { key: "Taxi", label: "Transport & Taxi", icon: "🚕", desc: "Bookings & fleet rides", kycType: "Service" },
  { key: "Construction", label: "Construction", icon: "🏗️", desc: "Building & contracting", kycType: "Service" },
  { key: "Law Firm", label: "Law Firm", icon: "⚖️", desc: "Legal services & retainers", kycType: "Consulting" },
  { key: "Accounting", label: "Accounting & Tax", icon: "📊", desc: "Bookkeeping, payroll & taxes", kycType: "Consulting" },
  { key: "Finance", label: "Finance & Advisory", icon: "💰", desc: "Investments & financial advice", kycType: "Consulting" },
  { key: "Education", label: "Tutoring & Lessons", icon: "✏️", desc: "Classes & private tutoring", kycType: "School" },
  { key: "Daycare", label: "Daycare & Nursery", icon: "🧸", desc: "Childcare & early years", kycType: "School" },
  { key: "Training", label: "Training & Bootcamps", icon: "🎓", desc: "Courses, skills & certification", kycType: "School" },
  { key: "Wedding", label: "Wedding Planning", icon: "💒", desc: "Plans, vendors & coordination", kycType: "Service" },
  { key: "Entertainment", label: "Entertainment", icon: "🎤", desc: "DJs, acts & performers", kycType: "Service" },
  { key: "Creative", label: "Creative Studio", icon: "🎨", desc: "Design, art & media", kycType: "Service" },
  { key: "Content", label: "Content Creator", icon: "📱", desc: "Media, sponsorships & fans", kycType: "Personal" },
  { key: "Journalist", label: "Media & News", icon: "📰", desc: "Publishing & subscriptions", kycType: "Nonprofit" },
  { key: "Farm", label: "Farm & Produce", icon: "🌾", desc: "Fresh produce & supply", kycType: "Retail" },
  { key: "Factory", label: "Manufacturing", icon: "🏭", desc: "Production & wholesale", kycType: "Service" },
  { key: "Wholesale", label: "Wholesale & Supply", icon: "📦", desc: "Bulk orders & B2B", kycType: "Retail" },
  { key: "Online Course", label: "Online Courses", icon: "💻", desc: "Digital products & lessons", kycType: "Service" },
  { key: "Subscription", label: "Subscriptions", icon: "🔄", desc: "Memberships & recurring", kycType: "Service" },
  { key: "Marketplace", label: "Marketplace", icon: "🏪", desc: "Multi-vendor storefronts", kycType: "Retail" },
  { key: "Newsletter", label: "Newsletter", icon: "📬", desc: "Subscribers & broadcasts", kycType: "Personal" },
];

export const CATEGORY_KEYS = BUSINESS_CATEGORIES.map(c => c.key);

export function getCategoryByKey(key) {
  return BUSINESS_CATEGORIES.find(c => c.key === key) || null;
}