function mapType(type) {
  const map = {
    hero_banner: "HeroBanner",
    menu_item: "MenuItem",
    category_pills: "CategoryPills",
    text_block: "TextBlock",
    image_block: "ImageBlock",
    menu_grid: "MenuGrid",
    button: "Button",
    divider: "Divider",
    rectangle: "Rectangle",
    ellipse: "Ellipse",
    line: "Line",
    arrow: "Arrow",
  };
  return map[type] || "Unknown";
}

function genComponentCode(comp) {
  const t = mapType(comp.type);
  const props = comp.props || {};
  const fills = comp.fills || [];
  const strokes = comp.strokes || [];
  const fillCSS = fills.length > 0
    ? (fills[0].color || "transparent")
    : "transparent";
  const strokeCSS = strokes.length > 0
    ? `${strokes[0].width || 0}px solid ${strokes[0].color || "transparent"}`
    : undefined;

  const style = {
    position: "absolute",
    left: comp.x,
    top: comp.y,
    width: comp.width,
    height: comp.height,
    borderRadius: comp.cornerRadius ?? 0,
    background: fillCSS,
    ...(strokeCSS ? { border: strokeCSS } : {}),
    ...(comp.rotation ? { transform: `rotate(${comp.rotation}deg)` } : {}),
    ...(comp.opacity != null && comp.opacity < 1 ? { opacity: comp.opacity } : {}),
  };

  return { component: t, props, style };
}

export function generateReactCode(designJSON) {
  const { meta, screens, navigation } = designJSON;
  const lines = [];

  lines.push("// Auto-generated by dukaDesk Canvas Editor");
  lines.push(`// App: ${meta.appName || "Untitled"}\n`);
  lines.push('import React, { useState } from "react";');
  lines.push('import "./styles.css";\n');

  Object.entries(screens).forEach(([id, screen]) => {
    lines.push(`const Screen_${id} = ({ data }) => (`);
    lines.push("  <div");
    lines.push(`    className="screen"`);
    lines.push(`    style={{ backgroundColor: "${screen.backgroundColor || "#FCF8FA"}" }}`);
    lines.push("  >");
    screen.components.forEach(comp => {
      const { component, style, props } = genComponentCode(comp);
      const styleStr = JSON.stringify(style, null, 6)
        .replace(/"([^"]+)":/g, "$1:")
        .replace(/"/g, "'");
      lines.push(`    <div style={${styleStr}}>`);
      lines.push(`      <${component} {...${JSON.stringify(props)}} />`);
      lines.push("    </div>");
    });
    lines.push("  </div>");
    lines.push(");\n");
  });

  lines.push("export default function App() {");
  if (navigation.tabs?.length > 0) {
    lines.push(`  const [screen, setScreen] = useState("${navigation.initialScreen}");`);
    lines.push("  return (");
    lines.push("    <div className=\"app-container\">");
    lines.push("      <div className=\"screen-area\">");
    lines.push("        {screen === \"initialScreen\" && <Screen_initialScreen data={{}} />}");
    Object.keys(screens).forEach(id => {
      lines.push(`        {screen === "${id}" && <Screen_${id} data={{}} />}`);
    });
    lines.push("      </div>");
    lines.push("      <div className=\"bottom-nav\">");
    navigation.tabs.forEach(tab => {
      lines.push(`        <div className="nav-tab" onClick={() => setScreen("${tab.screenId}")}>`);
      lines.push(`          <span>${tab.icon || "○"}</span>`);
      lines.push(`          <span>${tab.label}</span>`);
      lines.push("        </div>");
    });
    lines.push("      </div>");
    lines.push("    </div>");
    lines.push("  );");
  } else {
    const firstId = Object.keys(screens)[0];
    lines.push(`  return <Screen_${firstId} data={{}} />;`);
  }
  lines.push("}");

  return lines.join("\n");
}

export function generateHTMLCode(designJSON) {
  const { meta, screens, navigation } = designJSON;
  const lines = [];

  lines.push("<!DOCTYPE html>");
  lines.push('<html lang="en">');
  lines.push("<head>");
  lines.push("  <meta charset=\"UTF-8\" />");
  lines.push("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />");
  lines.push(`  <title>${meta.appName || "Untitled"}</title>`);
  lines.push("  <style>");
  lines.push("    * { margin: 0; padding: 0; box-sizing: border-box; }");
  lines.push("    body { font-family: 'Inter', sans-serif; background: #E8E5E0; display: flex; justify-content: center; }");
  lines.push("    .phone { width: 390px; height: 844px; background: #FCF8FA; border-radius: 24px; overflow: hidden; box-shadow: 0 8px 32px rgba(0,0,0,0.12); position: relative; margin: 20px; }");
  lines.push("    .screen { width: 100%; height: 100%; position: relative; overflow: hidden; }");
  lines.push("    .bottom-nav { display: flex; justify-content: space-around; align-items: center; padding: 4px 12px 8px; border-top: 1px solid rgba(200,197,205,0.3); position: absolute; bottom: 0; left: 0; right: 0; background: inherit; }");
  lines.push("    .nav-tab { display: flex; flex-direction: column; align-items: center; gap: 1px; cursor: pointer; padding: 4px 12px; border-radius: 16; font-size: 8px; }");
  lines.push("  </style>");
  lines.push("</head>");
  lines.push("<body>");
  lines.push("  <div class=\"phone\">");

  const firstId = Object.keys(screens)[0];
  const screen = screens[firstId];
  if (screen) {
    lines.push("    <div class=\"screen\" style={{ backgroundColor: '" + (screen.backgroundColor || "#FCF8FA") + "' }}>");
    screen.components.forEach(comp => {
      const fills = comp.fills || [];
      const fillColor = fills.length > 0 ? (fills[0].color || "transparent") : "transparent";
      const strokes = comp.strokes || [];
      const borderStyle = strokes.length > 0 ? `border: ${strokes[0].width || 0}px solid ${strokes[0].color || "transparent"};` : "";
      lines.push(`      <div style="position:absolute;left:${comp.x}px;top:${comp.y}px;width:${comp.width}px;height:${comp.height}px;background:${fillColor};${borderStyle}border-radius:${comp.cornerRadius ?? 0}px">`);
      lines.push(`        <!-- ${comp.type} -->`);
      lines.push("      </div>");
    });
    lines.push("    </div>");
  }

  if (navigation.tabs?.length > 0) {
    lines.push("    <div class=\"bottom-nav\">");
    navigation.tabs.forEach(tab => {
      lines.push(`      <div class="nav-tab">${tab.icon || "○"} ${tab.label}</div>`);
    });
    lines.push("    </div>");
  }

  lines.push("  </div>");
  lines.push("</body>");
  lines.push("</html>");

  return lines.join("\n");
}

export function generateJSON(designJSON) {
  return JSON.stringify(designJSON, null, 2);
}
